@ECHO OFF
REM Set variables
SET SOURCE=%~dp0
SET SOURCE=%SOURCE:~0,-1%
IF NOT DEFINED LOGDIR SET LOGDIR=%SystemRoot%\TEMP

REM Resources
REM http://support.citrix.com/proddocs/topic/xendesktop-7/cds-install-command.html
REM CONTROLLER,DESKTOPSTUDIO,DESKTOPDIRECTOR,LICENSESERVER,STOREFRONT

SET OPTIONS=
SET OPTIONS=/QUIET
SET OPTIONS=%OPTIONS% /NOREBOOT
SET OPTIONS=%OPTIONS% /CONFIGURE_FIREWALL
SET OPTIONS=%OPTIONS% /COMPONENTS CONTROLLER,DESKTOPSTUDIO,DESKTOPDIRECTOR
SET OPTIONS=%OPTIONS% /ENABLEREMOTEASSISTANCE
SET OPTIONS=%OPTIONS% /NOSQL

PUSHD "%SOURCE%\x64\XenDesktop Setup"
START /WAIT XenDesktopServerSetup.exe %OPTIONS%
POPD

